import Head from 'next/head'
import Temperatura from './components/Temperatura'

export default function Home () {
  return (
    <>
      <Head>
        <title>Grupo 20 ACE2</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='flex mb-12 p-3 bg-gray-900'>
          <h1 className='text-xl font-semibold text-center text-white'>
            Grupo 20 ACE2
          </h1>
        </div>
        <div className='flex justify-around'>
          <div className='w-64'>
            <Temperatura />
          </div>
          <div className='w-64'>
            <Temperatura />
          </div>
          <div className='w-64'>
            <Temperatura />
          </div>
        </div>
      </main>
    </>
  )
}
