import Navbar from '@/components/Navbar'
import Head from 'next/head'
import { useState } from 'react'
import { Constants } from '@/constants'

export default function Home () {
  const [rest, setRest] = useState(5)

  const handlerRest = (e) => {
    setRest(Number.parseInt(e.target.value))
  }

  const handlerSend = () => {
    fetch(`http://${Constants.IP_ADDRESS}/api/sendRest`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        rest
      })
    })
      .then(res => res.json())
      .then(data => {
        console.log(data)
      })
  }

  return (
    <>
      <Head>
        <title>Pomodoro G20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="bg-bgred h-screen">
        <section className="flex flex-col">
          <div className="flex items-center justify-center">
            <div className="flex flex-col mt-11 drop-shadow-xl md:flex-row">
              { /*
              <div className="mx-4">
                <h1 className="text-xl text-center font-bold text-white underline decoration-green-300 mb-4">
                  Pomodoro
                </h1>
                <input
                  type="number"
                  defaultValue={25}
                  className="w-auto text-center text-2xl font-bold text-green-800 bg-gray-100 rounded-lg"
                />
              </div>
              */ }
              <div className="mx-4">
                <h1 className="text-xl text-center font-bold text-white underline decoration-green-300 mb-4">
                  Descanso
                </h1>
                <input
                  type="number"
                  defaultValue={rest}
                  className="text-center text-2xl font-bold text-green-800 bg-gray-100 rounded-lg w-full appearance-none"
                  onChange={handlerRest}
                  min={0}
                  max={60}
                />
              </div>
            </div>
          </div>
          <div className="flex items-center justify-center mt-10">
            <button className="bg-green-400 w-48 h-12 font-bold text-white ring-2 ring-green-700 rounded"
              onClick={handlerSend}>
              Enviar
            </button>
          </div>
        </section>
      </main>
    </>
  )
}
