-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 16:27:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ace2_proyecto1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ace2_proyecto1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ace2_proyecto1` DEFAULT CHARACTER SET utf8 ;
USE `ace2_proyecto1` ;

-- -----------------------------------------------------
-- Table `ace2_proyecto1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ace2_proyecto1`.`usuario` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `fullname` VARCHAR(50) NOT NULL,
  `pass` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ace2_proyecto1`.`pomodoro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ace2_proyecto1`.`pomodoro` (
  `podomoro_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `work_time` INT NOT NULL DEFAULT 25,
  `rest_time` INT NOT NULL DEFAULT 5,
  `init_date` DATETIME NOT NULL,
  `usuario_user_id` INT NOT NULL,
  PRIMARY KEY (`podomoro_id`, `usuario_user_id`),
  INDEX `fk_pomodoro_usuario_idx` (`usuario_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_pomodoro_usuario`
    FOREIGN KEY (`usuario_user_id`)
    REFERENCES `ace2_proyecto1`.`usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ace2_proyecto1`.`penalizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ace2_proyecto1`.`penalizacion` (
  `id_penalizacion` INT NOT NULL AUTO_INCREMENT,
  `minute` INT NOT NULL,
  `second` INT NOT NULL,
  `cicle` INT NOT NULL,
  `penalty_time` INT NOT NULL,
  `penalty_date` DATETIME NOT NULL DEFAULT NOW(),
  `pomodoro_podomoro_id` INT NOT NULL,
  `pomodoro_usuario_user_id` INT NOT NULL,
  PRIMARY KEY (`id_penalizacion`, `pomodoro_podomoro_id`, `pomodoro_usuario_user_id`),
  INDEX `fk_penalizacion_pomodoro1_idx` (`pomodoro_podomoro_id` ASC, `pomodoro_usuario_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_penalizacion_pomodoro1`
    FOREIGN KEY (`pomodoro_podomoro_id` , `pomodoro_usuario_user_id`)
    REFERENCES `ace2_proyecto1`.`pomodoro` (`podomoro_id` , `usuario_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
